name: cycle5
channels:
  - conda-forge
  - bokeh
dependencies:
  - numba=0.60.0
  - numpy=1.26.4
  - scipy=1.11.4
  - bokeh=3.0.2
  - photochem=0.6.7
  - mpi4py=4.0.1
  - dill=0.3.9
  - tqdm=4.66.5
  - astropy=6.1.4
  - pandas=2.2.3
  - xarray=2024.9.0
  - pymultinest=2.12
  - virga-exo=0.4
  - matplotlib
  - pip
  - wget
  - tar
  - unzip
  - jupyter
